egress_ports: 4
speed: 50Gbit
mtu: 4096
buffer_size: 131068
mode:
  #variant: StaticHash
  variant: Dfls
  flowlet_size: 4096
ingress_ports:
- src_ip: 1.1.1.1
  flows:
  - volume: 10GB
    destination: 1.1.1.30
    src_port: 100
- src_ip: 1.1.1.1
  flows:
  - volume: 10GB
    destination: 1.1.1.30
    src_port: 100
    #destination: 1.1.1.40
    #src_port: 20011
- src_ip: 2.2.2.2
  flows:
  - volume: 10GB
    destination: 2.2.2.30
    src_port: 300
- src_ip: 2.2.2.2
  flows:
  - volume: 10GB
    destination: 2.2.2.4
    src_port: 400